name: Continuous lighthouse test
on: 
  push:
    branches:
    - master
jobs:
  build:
    name: Setting up and run action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
    - name: Npm install
      run: npm install
    - name: Lighthouse test in prod
      run: npm run ci:lighthouse
